import type { Metadata } from "next";
import { Golos_Text } from "next/font/google";
import localFont from "next/font/local";
import { Header } from "@/components/header";
import "./globals.css";

const font = Golos_Text({ subsets: ["latin"] });

const myFont = localFont({
  src: "../assets/font/Sans.woff",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="en">
      <body className={font.className}>
        {/* <div className="absolute top-[-25%] left-[20%] -z-10 w-[18rem] h-[39rem] rotate-[66deg] bg-indigo-400 blur-[120px]" />
        <div className="absolute top-[20%] left-[60%] -z-10 w-[18rem] h-[39rem] rotate-[66deg] bg-indigo-400 blur-[120px]" /> */}
        <Header />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
