import type { Metadata } from "next";
import { Golos_Text } from "next/font/google";
import localFont from "next/font/local";
import { Header } from "@/components/header";
import "./globals.css";

const font = Golos_Text({ subsets: ["latin"] });

const myFont = localFont({
  src: "../assets/font/Sans.woff",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
